[package]
name = "port_sniffer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
bpaf = {version = "0.9.12" , features=["derive", "bright-color"]}